stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/dataset.csv
    - src/preprocess.py
    outs:
    - data/processed
  train_models:
    cmd: python src/train.py
    deps:
    - data/processed/processed.csv
    - src/train.py
    - src/config.py
    - src/utils.py
    - src/preprocess.py
    params:
      - train
      - models
    outs:
      - models
    metrics:
      - metrics/metrics.json:
          cache: false
  evaluate:
    cmd: python src/eval.py
    deps:
      - src/eval.py
      - models/best_model.pkl
      - data/processed/processed.csv
    metrics:
      - metrics/best_model_metrics.json:
          cache: false
