stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - data/raw/dataset.csv
      - src/preprocess.py
    outs:
      - data/processed/processed.csv

  train_models:
    foreach: ${models}
    do:
      cmd: CONFIG_PROFILE=test python src/train_single.py --model ${key}
      deps:
        - data/processed/processed.csv
        - src/train_single.py
        - src/base_config.py
        - src/utils.py
      params:
        - train
        - models
      outs:
        - models/${key}.pkl
      metrics:
        - metrics/train_models/${key}_metrics.json:
            cache: false


  select_best:
    cmd: CONFIG_PROFILE=test python src/select_best.py
    deps:
      - src/select_best.py
      - metrics/train_models
    metrics:
      - metrics/best_model_metrics.json:
          cache: false
    outs:
      - models/best_model.pkl

  evaluate:
    cmd: CONFIG_PROFILE=test python src/eval.py
    deps:
      - src/eval.py
      - models/best_model.pkl
      - data/processed/processed.csv
    metrics:
      - metrics/best_model_advanced_metrics.json:
          cache: false

  report:
    cmd: python src/generate_report.py
    deps:
      - src/generate_report.py
      - metrics/best_model_advanced_metrics.json
      - metrics/train_models
    outs:
      - docs/experiments.md:
          cache: false
      - docs/assets/images:
          cache: false