[tool.poetry]
name = "itmo_enginiring_practices_ml"
version = "0.0.1"
description = ""
authors = ["Rustam Akimov <akirusprod@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
jupyterlab = "^4.4.10"
loguru = "^0.7.3"
matplotlib = "^3.10.7"
mkdocs = "^1.6.1"
notebook = "^7.4.7"
pandas = "^2.3.3"
pip = "^25.3"
pytest = "^9.0.1"
python-dotenv = "^1.2.1"
scikit-learn = "^1.7.2"
tqdm = "^4.67.1"
typer = "^0.20.0"
dvc = "^3.64.0"
tensorboard = "^2.20.0"
tensorboardx = "^2.6.4"
pytelegrambotapi = "^4.29.1"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
isort = "^6.0"
ruff = "^0.0"
mypy = "^1.0"
pre-commit = "^4.4.0"
bandit = "^1.8.6"
pbr = "^7.0.3"
types-pyyaml = "^6.0.12.20250915"

[tool.black]
line-length = 88
target-version = ["py310"]

[tool.isort]
profile = "black"

[tool.ruff]
select = ["E", "F", "W"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
exclude = ["venv", "tests"]

[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

