[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "itmo_enginiring_practices_ml"
version = "0.0.1"
description = "My homework"
authors = [
  { name = "Rustam Akimov" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.10.0"


[tool.ruff]
line-length = 99
src = ["itmo_enginiring_practices_ml"]
include = ["pyproject.toml", "itmo_enginiring_practices_ml/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["itmo_enginiring_practices_ml"]
force-sort-within-sections = true

